modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="messenger_crow"
version="1.3.2"
displayName="Messenger Crow"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Devrune, MCreator"
description="A new form of trade!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.messenger_crow]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.messenger_crow]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.2,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration